local list = require("src.datatypes.list")
local dsu = require("src.datatypes.dsu")
local stack = require("src.datatypes.stack")
local queue = require("src.datatypes.queue")

local s = stack.Stack.new()
s.push(5)
s.push(2)
s.push(10)
print(s.pop())